[buildPlans.IosevkaCode]
family = "Iosevka Code"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaCode.variants.design]
f = "flat-hook-serifless"
t = "flat-hook"

[buildPlans.IosevkaCode.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCode.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCode.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCode.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaCode.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaCode.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaCode.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaCode.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaCode.widths.Normal]
shape = 600
menu = 5
css = "normal"
