[buildPlans.IosevkaTermCode]
family = "Iosevka Term Code"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaTermCode.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTermCode.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaTermCode.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaTermCode.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaTermCode.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaTermCode.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaTermCode.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaTermCode.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaTermCode.widths.Normal]
shape = 600
menu = 5
css = "normal"
